language: node_js
git:
  depth: 3
node_js:
  - node
dist: trusty
sudo: false
install: npm install

cache:
  directories:
    - node_modules

script:
  - npm test
  - gulp
  - cp index.html 404.html
  - echo $DEPLOY_CNAME > dist/CNAME

notifications:
  email:       false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist
  on:
    branch: master